// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OprawaObrazow.Data;

#nullable disable

namespace OprawaObrazow.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250601134532_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OprawaObrazow.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("clients_pk");

                    b.ToTable("clients", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit")
                        .HasColumnName("is_delivered");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("deliveries_pk");

                    b.HasIndex(new[] { "SupplierId" }, "IX_deliveries_supplier_id");

                    b.ToTable("deliveries", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Frame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<int>("Color")
                        .HasColumnType("int")
                        .HasColumnName("color");

                    b.Property<bool>("HasDecoration")
                        .HasColumnType("bit")
                        .HasColumnName("has_decoration");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("storage_location");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("frame_pk");

                    b.HasIndex(new[] { "SupplierId" }, "IX_frames_supplier_id");

                    b.ToTable("frames", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.FramePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<int>("FrameId")
                        .HasColumnType("int")
                        .HasColumnName("frame_id");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit")
                        .HasColumnName("is_damaged");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit")
                        .HasColumnName("is_in_stock");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasColumnName("length");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("storage_location");

                    b.HasKey("Id")
                        .HasName("frame_pieces_pk");

                    b.HasIndex(new[] { "DeliveryId" }, "IX_frame_pieces_delivery_id");

                    b.HasIndex(new[] { "FrameId" }, "IX_frame_pieces_frame_id");

                    b.HasIndex(new[] { "OrderId" }, "IX_frame_pieces_order_id");

                    b.ToTable("frame_pieces", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit")
                        .HasColumnName("is_closed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit")
                        .HasColumnName("is_finished");

                    b.Property<int>("PictureHeight")
                        .HasColumnType("int")
                        .HasColumnName("picture_height");

                    b.Property<int>("PictureWidth")
                        .HasColumnType("int")
                        .HasColumnName("picture_width");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("orders_pk");

                    b.HasIndex(new[] { "ClientId" }, "IX_orders_client_id");

                    b.ToTable("orders", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly?>("LastSupply")
                        .HasColumnType("date")
                        .HasColumnName("last_supply");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("suppliers_pk");

                    b.ToTable("suppliers", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.ToTable("users", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Delivery", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Models.Supplier", "Supplier")
                        .WithMany("Deliveries")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("deliveries_suppliers_fk");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Frame", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Models.Supplier", "Supplier")
                        .WithMany("Frames")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("frame_suppliers_id_fk");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.FramePiece", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Models.Delivery", "Delivery")
                        .WithMany("FramePieces")
                        .HasForeignKey("DeliveryId")
                        .IsRequired()
                        .HasConstraintName("frame_pieces_deliveries_fk");

                    b.HasOne("OprawaObrazow.Data.Models.Frame", "Frame")
                        .WithMany("FramePieces")
                        .HasForeignKey("FrameId")
                        .IsRequired()
                        .HasConstraintName("frame_pieces_frame_id_fk");

                    b.HasOne("OprawaObrazow.Data.Models.Order", "Order")
                        .WithMany("FramePieces")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("frame_pieces_orders_id_fk");

                    b.Navigation("Delivery");

                    b.Navigation("Frame");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Order", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("orders_clients_id_fk");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Delivery", b =>
                {
                    b.Navigation("FramePieces");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Frame", b =>
                {
                    b.Navigation("FramePieces");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Order", b =>
                {
                    b.Navigation("FramePieces");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Models.Supplier", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
