// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OprawaObrazow.Data;

#nullable disable

namespace OprawaObrazow.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OprawaObrazow.Data.Color.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("colors_pk");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("colors", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Frame.Frame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.Property<bool>("HasDecoration")
                        .HasColumnType("bit")
                        .HasColumnName("has_decoration");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("frame_pk");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("frames_code_unique")
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex(new[] { "ColorId" }, "IX_frames_color_id");

                    b.HasIndex(new[] { "SupplierId" }, "IX_frames_supplier_id");

                    b.ToTable("frames", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.FramePiece.FramePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FrameId")
                        .HasColumnType("int")
                        .HasColumnName("frame_id");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit")
                        .HasColumnName("is_damaged");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit")
                        .HasColumnName("is_in_stock");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasColumnName("length");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("storage_location")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("frame_pieces_pk");

                    b.HasIndex(new[] { "FrameId" }, "IX_frame_pieces_frame_id");

                    b.HasIndex(new[] { "OrderId" }, "IX_frame_pieces_order_id");

                    b.ToTable("frame_pieces", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("client_name");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PictureHeight")
                        .HasColumnType("int")
                        .HasColumnName("picture_height");

                    b.Property<int>("PictureWidth")
                        .HasColumnType("int")
                        .HasColumnName("picture_width");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("orders_pk");

                    b.ToTable("orders", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Supplier.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("suppliers_pk");

                    b.ToTable("suppliers", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "oprawa");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Frame.Frame", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Color.Color", "Color")
                        .WithMany("Frames")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OprawaObrazow.Data.Supplier.Supplier", "Supplier")
                        .WithMany("Frames")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("frame_suppliers_id_fk");

                    b.Navigation("Color");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OprawaObrazow.Data.FramePiece.FramePiece", b =>
                {
                    b.HasOne("OprawaObrazow.Data.Frame.Frame", "Frame")
                        .WithMany("FramePieces")
                        .HasForeignKey("FrameId")
                        .IsRequired()
                        .HasConstraintName("frame_pieces_frame_id_fk");

                    b.HasOne("OprawaObrazow.Data.Order.Order", "Order")
                        .WithMany("FramePieces")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("frame_pieces_orders_id_fk");

                    b.Navigation("Frame");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Color.Color", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Frame.Frame", b =>
                {
                    b.Navigation("FramePieces");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Order.Order", b =>
                {
                    b.Navigation("FramePieces");
                });

            modelBuilder.Entity("OprawaObrazow.Data.Supplier.Supplier", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
